include: package:very_good_analysis/analysis_options.4.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    directives_ordering: false
    prefer_if_elements_to_conditional_expressions: false
    use_build_context_synchronously: false
    avoid_dynamic_calls: false
